# Generated by Django 5.0.dev20230329142653 on 2023-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(max_length=10000),
        ),
    ]
