# Generated by Django 4.1.7 on 2023-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_post_image_alter_post_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.FileField(
                blank=True, default="", null=True, upload_to="media/"
            ),
        ),
    ]
