# Generated by Django 4.1.7 on 2023-03-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("id_num", models.IntegerField(verbose_name="ID Number")),
                ("species", models.CharField(max_length=50)),
                ("breed", models.CharField(max_length=50)),
                ("weight", models.CharField(max_length=25)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("intake_date", models.DateField(verbose_name="Intake Date")),
                ("estimated_age", models.IntegerField(default=0)),
                ("image", models.FileField(default="", upload_to="uploads/%Y/%m/")),
                ("notes", models.TextField()),
                (
                    "visible_on_website",
                    models.BooleanField(
                        default=True, verbose_name="Display on website?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/%Y/%m/")),
                ("image_desc", models.CharField(max_length=100)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listing.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregnant", models.BooleanField(verbose_name="Pregnant?")),
                ("microchips", models.BooleanField(verbose_name="Microchipped?")),
                (
                    "good_with_people",
                    models.BooleanField(verbose_name="Good with people?"),
                ),
                (
                    "good_with_same_species",
                    models.BooleanField(
                        verbose_name="Good with others of the same species?"
                    ),
                ),
                ("bite_history", models.BooleanField(verbose_name="Bite history?")),
                (
                    "surrendered_by_owner",
                    models.BooleanField(verbose_name="Surrendered by owner?"),
                ),
                ("housebroken", models.BooleanField(verbose_name="Housebroken?")),
                (
                    "reason_for_surrender",
                    models.TextField(
                        blank=True,
                        verbose_name="If surrendered by owner, why? (Optional)",
                    ),
                ),
                (
                    "condition_of_teeth",
                    models.TextField(
                        blank=True, verbose_name="Condition of teeth (Optional)"
                    ),
                ),
                (
                    "condition_of_skin",
                    models.TextField(
                        blank=True,
                        verbose_name="Obvious issues or abnormalities? (Optional)",
                    ),
                ),
                (
                    "animal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="listing.animal"
                    ),
                ),
            ],
        ),
    ]
