# Generated by Django 4.1.7 on 2023-03-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("id_num", models.IntegerField()),
                ("species", models.CharField(max_length=50)),
                ("breed", models.CharField(max_length=50)),
                ("weight", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                ("intake_date", models.DateTimeField(verbose_name="Intake Date")),
                ("estimated_dob", models.DateTimeField(verbose_name="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("V", "Available"),
                            ("A", "Adopted"),
                            ("U", "Unavailable"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/%Y/%m/")),
                ("image_desc", models.CharField(max_length=100)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listing.animal"
                    ),
                ),
            ],
        ),
    ]
