# Generated by Django 4.1.7 on 2023-03-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="estimated_dob",
            field=models.DateTimeField(verbose_name="Estimated Date of Birth"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Adopted", "Adopted"),
                    ("Unavailable", "Unavailable"),
                ],
                max_length=20,
            ),
        ),
    ]
