# Generated by Django 4.1.7 on 2023-03-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0002_alter_animal_estimated_dob_alter_animal_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="weight",
            field=models.CharField(max_length=25),
        ),
    ]
